services:
  nginx:
    image: nginx:latest
    container_name: nginx_deploy_do_an
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/dist:/usr/share/nginx/html # Client user
      - ./nginx/admin_dist:/usr/share/nginx/admin # Admin
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx # Để lưu log
    environment:
      - TZ=Asia/Ho_Chi_Minh
