services:
  nginx:
    image: nginx:latest
    container_name: nginx_deploy_do_an
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Thêm cổng HTTPS
    volumes:
      - /var/www/techworks-client:/var/www/techworks-client # Client user
      - /var/www/techworks-admin:/var/www/techworks-admin # Admin
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # Cấu hình Nginx
      - ./nginx/logs:/var/log/nginx # Log
      - /etc/letsencrypt:/etc/letsencrypt:ro # Chứng chỉ SSL
      - /etc/nginx/dist:/etc/nginx/dist:ro # File lỗi 50x.html
    environment:
      - TZ=Asia/Ho_Chi_Minh